    build:
      context: ./mern/frontend
    container_name: froncont
    networks:
      - mynet
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./mern/backend
    container_name: backcont
    networks:
      - mynet
    depends_on:
      - database
    ports:
      - "5050:5050"

  database:
    image: mongo:latest
    container_name: dbcont
    volumes:
      - myvol:/data/db
    networks:
      - mynet

volumes:
  myvol:

networks:
  mynet:
